//LOGIN;
export const SYNC_STORAGE_BEGIN = 'SYNC_STORAGE_BEGIN';
export const SYNC_STORAGE_SUCCESS = 'SYNC_STORAGE_SUCCESS'
export const STORAGE_EMPTY = 'STORAGE_EMPTY';
export const POST_CLIENT_LOGIN_BEGIN = 'POST_CLIENT_LOGIN_BEGIN';
export const POST_VALIDATE_CLIENT_LOGIN = 'POST_VALIDATE_CLIENT_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const POST_CLIENT_LOGIN_FAILURE = 'POST_CLIENT_LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

//HOME
//BALANCE INQUIRY
export const GET_BALANCE_BEGIN = 'GET_BALANCE_BEGIN';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAILURE = 'GET_BALANCE_FAILURE';
//ACCOUNT STATEMENT
export const GET_ACCOUNT_STATEMENT_BEGIN = 'GET_ACCOUNT_STATEMENT_BEGIN';
export const GET_ACCOUNT_STATEMENT_SUCCESS = 'GET_ACCOUNT_STATEMENT_SUCCESS';
export const GET_ACCOUNT_STATEMENT_FAILURE = 'GET_ACCOUNT_STATEMENT_FAILURE';

//TRANSFER
//REGISTER DESTINATION ACCOUNT
export const CHECK_CLIENT_DESTINATION_BEGIN = 'CHECK_CLIENT_DESTINATION_BEGIN';
export const CHECK_CLIENT_DESTINATION_SUCCESS = 'CHECK_CLIENT_DESTINATION_SUCCESS';
export const CHECK_CLIENT_DESTINATION_EMPTY = 'CHECK_CLIENT_DESTINATION_EMPTY';
export const CHECK_CLIENT_DESTINATION_FAILURE = 'CHECK_CLIENT_DESTINATION_FAILURE';
export const SAVE_CLIENT_DESTINATION_BEGIN = 'SAVE_CLIENT_DESTINATION_BEGIN';
export const SAVE_CLIENT_DESTINATION_SUCCESS = 'SAVE_CLIENT_DESTINATION_SUCCESS';
export const SAVE_CLIENT_DESTINATION_FAILURE = 'SAVE_CLIENT_DESTINATION_FAILURE';
export const GET_LIST_CLIENT_DESTINATION_BEGIN = 'GET_LIST_CLIENT_DESTINATION_BEGIN';
export const GET_LIST_CLIENT_DESTINATION_SUCCESS = 'GET_LIST_CLIENT_DESTINATION_SUCCESS';
export const GET_LIST_CLIENT_DESTINATION_FAILURE = 'GET_LIST_CLIENT_DESTINATION_FAILURE';
export const TRANSFER_PROCESS_BEGIN = 'TRANSFER_PROCESS_BEGIN';
export const TRANSFER_PROCESS_SUCCESS = 'TRANSFER_PROCESS_SUCCESS';
export const TRANSFER_PROCESS_FAILURE = 'TRANSFER_PROCESS_FAILURE';