//REGISTER
//INPUT PAN
export const CHECK_PAN_BEGIN = 'CHECK_PAN_BEGIN';
export const CHECK_PAN_FAILURE = 'CHECK_PAN_FAILURE';
export const CHECK_PAN_SUCCESS = 'CHECK_PAN_SUCCESS';
export const GET_REGISTER_TOKEN_BEGIN = 'GET_REGISTER_TOKEN_BEGIN';
export const GET_REGISTER_TOKEN_SUCCESS = 'GET_REGISTER_TOKEN_SUCCESS';
export const GET_REGISTER_TOKEN_FAILURE = 'GET_REGISTER_TOKEN_FAILURE';
export const VALIDATE_REGISTER_TOKEN_BEGIN = 'VALIDATE_REGISTER_TOKEN_BEGIN';
export const VALIDATE_REGISTER_TOKEN_SUCCESS = 'VALIDATE_REGISTER_TOKEN_SUCCESS';
export const VALIDATE_REGISTER_TOKEN_FAILURE = 'VALIDATE_REGISTER_TOKEN_FAILURE';
export const VALIDATE_PIN_BEGIN = 'VALIDATE_PIN_BEGIN';
export const VALIDATE_PIN_SUCCESS = 'VALIDATE_PIN_SUCCESS';
export const VALIDATE_PIN_FAILURE = 'VALIDATE_PIN_FAILURE';
export const CHECK_CUSTOMER_BEGIN = "CHECK_CUSTOMER_BEGIN";
export const CHECK_CUSTOMER_SUCCESS = "CHECK_CUSTOMER_SUCCESS";
export const CHECK_CUSTOMER_FAILURE = "CHECK_CUSTOMER_FAILURE";
export const CHECK_USERNAME_BEGIN = "CHECK_USERNAME_BEGIN";
export const CHECK_USERNAME_SUCCESS = "CHECK_USERNAME_SUCCESS";
export const CHECK_USERNAME_FAILURE = "CHECK_USERNAME_FAILURE";
export const CREATE_NEW_USER_BEGIN = "CREATE_NEW_USER_BEGIN";
export const CREATE_NEW_USER_SUCCESS = "CREATE_NEW_USER_SUCCESS";
export const CREATE_NEW_USER_FAILURE = "CREATE_NEW_USER_FAILURE";
export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const RESET_USER_PASSWORD_BEGIN = "RESET_USER_PASSWORD_BEGIN";
export const RESET_USER_PASSWORD_SUCCESS = "RESET_USER_PASSWORD_SUCCESS";
export const RESET_USER_PASSWORD_FAILURE = "RESET_USER_PASSWORD_FAILURE";
export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const GET_LOGIN_OTP_BEGIN = 'GET_LOGIN_OTP_BEGIN';
export const GET_LOGIN_OTP_SUCCESS = 'GET_LOGIN_OTP_SUCCESS';
export const GET_LOGIN_OTP_FAILURE = 'GET_LOGIN_OTP_FAILURE';
export const VALIDATE_LOGIN_TOKEN_BEGIN = 'VALIDATE_LOGIN_TOKEN_BEGIN';
export const VALIDATE_LOGIN_TOKEN_SUCCESS = 'VALIDATE_LOGIN_TOKEN_SUCCESS';
export const VALIDATE_LOGIN_TOKEN_FAILURE = 'VALIDATE_LOGIN_TOKEN_FAILURE';
export const SKIP_EASYPIN_LOGIN = 'SKIP_EASYPIN_LOGIN';

//LOGIN;
export const SYNC_STORAGE_BEGIN = 'SYNC_STORAGE_BEGIN';
export const SYNC_STORAGE_SUCCESS = 'SYNC_STORAGE_SUCCESS'
export const STORAGE_EMPTY = 'STORAGE_EMPTY';
export const POST_CLIENT_LOGIN_BEGIN = 'POST_CLIENT_LOGIN_BEGIN';
export const POST_VALIDATE_CLIENT_LOGIN = 'POST_VALIDATE_CLIENT_LOGIN';
export const EASY_PIN_LOGIN = 'EASY_PIN_LOGIN';
// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const POST_CLIENT_LOGIN_FAILURE = 'POST_CLIENT_LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

//EASYPINLOGIN
export const VALIDATE_EASYPIN_LOGIN = 'VALIDATE_EASYPIN_LOGIN';

//HOME
//BALANCE INQUIRY
export const GET_BALANCE_BEGIN = 'GET_BALANCE_BEGIN';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAILURE = 'GET_BALANCE_FAILURE';
//ACCOUNT STATEMENT
export const GET_ACCOUNT_STATEMENT_BEGIN = 'GET_ACCOUNT_STATEMENT_BEGIN';
export const GET_ACCOUNT_STATEMENT_SUCCESS = 'GET_ACCOUNT_STATEMENT_SUCCESS';
export const GET_ACCOUNT_STATEMENT_FAILURE = 'GET_ACCOUNT_STATEMENT_FAILURE';

//TRANSFER
export const GET_BANK_LIST_BEGIN = 'GET_BANK_LIST_BEGIN';
export const GET_BANK_LIST_SUCCESS = 'GET_BANK_LIST_SUCCESS';
export const GET_BANK_LIST_FAILURE = 'GET_BANK_LIST_FAILURE';
export const CHECK_ACCOUNT_NUMBER_BEGIN = 'CHECK_ACCOUNT_NUMBER_BEGIN';
export const CHECK_ACCOUNT_NUMBER_SUCCESS = 'CHECK_ACCOUNT_NUMBER_SUCCESS';
export const CHECK_ACCOUNT_NUMBER_FAILURE = 'CHECK_ACCOUNT_NUMBER_FAILURE';
export const EMPTY_TARGET_ACCOUNT = 'EMPTY_TARGET_ACCOUNT';
export const SET_SOURCE_ACCOUNT_SUCCESS = 'SET_SOURCE_ACCOUNT_SUCCESS';
export const SET_TRANSFER_AMOUNT = 'SET_TRANSFER_AMOUNT';
export const SET_TRANSFER_NOTE = 'SET_TRANSFER_NOTE';
export const GET_METHOD_LIST_BEGIN = 'GET_METHOD_LIST_BEGIN';
export const GET_METHOD_LIST_SUCCESS = 'GET_METHOD_LIST_SUCCESS';
export const GET_METHOD_LIST_FAILURE = 'GET_METHOD_LIST_FAILURE';
export const SET_SEND_METHOD = 'SET_SEND_METHOD';
export const CLEAR_SEND_METHOD = 'CLEAR_SEND_METHOD';
export const TRANSFER_BEGIN = 'TRANFER_BEGIN'
export const TRANSFER_SUCCESS = 'TRANFER_SUCCESS'
export const TRANSFER_FAILURE = 'TRANFER_FAILURE'