//REGISTER
//INPUT PAN
export const CHECK_PAN_BEGIN = 'CHECK_PAN_BEGIN';
export const CHECK_PAN_FAILURE = 'CHECK_PAN_FAILURE';
export const CHECK_PAN_SUCCESS = 'CHECK_PAN_SUCCESS';
export const GET_REGISTER_TOKEN_BEGIN = 'GET_REGISTER_TOKEN_BEGIN';
export const GET_REGISTER_TOKEN_SUCCESS = 'GET_REGISTER_TOKEN_SUCCESS';
export const GET_REGISTER_TOKEN_FAILURE = 'GET_REGISTER_TOKEN_FAILURE';
export const VALIDATE_REGISTER_TOKEN_BEGIN = 'VALIDATE_REGISTER_TOKEN_BEGIN';
export const VALIDATE_REGISTER_TOKEN_SUCCESS = 'VALIDATE_REGISTER_TOKEN_SUCCESS';
export const VALIDATE_REGISTER_TOKEN_FAILURE = 'VALIDATE_REGISTER_TOKEN_FAILURE';
export const VALIDATE_PIN_BEGIN = 'VALIDATE_PIN_BEGIN';
export const VALIDATE_PIN_SUCCESS = 'VALIDATE_PIN_SUCCESS';
export const VALIDATE_PIN_FAILURE = 'VALIDATE_PIN_FAILURE';
export const CHECK_CUSTOMER_BEGIN = "CHECK_CUSTOMER_BEGIN";
export const CHECK_CUSTOMER_SUCCESS = "CHECK_CUSTOMER_SUCCESS";
export const CHECK_CUSTOMER_FAILURE = "CHECK_CUSTOMER_FAILURE";
export const CHECK_USERNAME_BEGIN = "CHECK_USERNAME_BEGIN";
export const CHECK_USERNAME_SUCCESS = "CHECK_USERNAME_SUCCESS";
export const CHECK_USERNAME_FAILURE = "CHECK_USERNAME_FAILURE";
export const CREATE_NEW_USER_BEGIN = "CREATE_NEW_USER_BEGIN";
export const CREATE_NEW_USER_SUCCESS = "CREATE_NEW_USER_SUCCESS";
export const CREATE_NEW_USER_FAILURE = "CREATE_NEW_USER_FAILURE";
export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const RESET_USER_PASSWORD_BEGIN = "RESET_USER_PASSWORD_BEGIN";
export const RESET_USER_PASSWORD_SUCCESS = "RESET_USER_PASSWORD_SUCCESS";
export const RESET_USER_PASSWORD_FAILURE = "RESET_USER_PASSWORD_FAILURE";

//LOGIN;
export const SYNC_STORAGE_BEGIN = 'SYNC_STORAGE_BEGIN';
export const SYNC_STORAGE_SUCCESS = 'SYNC_STORAGE_SUCCESS'
export const STORAGE_EMPTY = 'STORAGE_EMPTY';
export const POST_CLIENT_LOGIN_BEGIN = 'POST_CLIENT_LOGIN_BEGIN';
export const POST_VALIDATE_CLIENT_LOGIN = 'POST_VALIDATE_CLIENT_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const POST_CLIENT_LOGIN_FAILURE = 'POST_CLIENT_LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

//HOME
//BALANCE INQUIRY
export const GET_BALANCE_BEGIN = 'GET_BALANCE_BEGIN';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAILURE = 'GET_BALANCE_FAILURE';
//ACCOUNT STATEMENT
export const GET_ACCOUNT_STATEMENT_BEGIN = 'GET_ACCOUNT_STATEMENT_BEGIN';
export const GET_ACCOUNT_STATEMENT_SUCCESS = 'GET_ACCOUNT_STATEMENT_SUCCESS';
export const GET_ACCOUNT_STATEMENT_FAILURE = 'GET_ACCOUNT_STATEMENT_FAILURE';

//TRANSFER
//REGISTER DESTINATION ACCOUNT
export const CHECK_CLIENT_DESTINATION_BEGIN = 'CHECK_CLIENT_DESTINATION_BEGIN';
export const CHECK_CLIENT_DESTINATION_SUCCESS = 'CHECK_CLIENT_DESTINATION_SUCCESS';
export const CHECK_CLIENT_DESTINATION_EMPTY = 'CHECK_CLIENT_DESTINATION_EMPTY';
export const CHECK_CLIENT_DESTINATION_FAILURE = 'CHECK_CLIENT_DESTINATION_FAILURE';
export const GET_CLIENT_TOKEN_BEGIN = 'GET_CLIENT_TOKEN_BEGIN';
export const GET_CLIENT_TOKEN_SUCCESS = 'GET_CLIENT_TOKEN_SUCCESS';
export const GET_CLIENT_TOKEN_FAILURE = 'GET_CLIENT_TOKEN_FAILURE';
export const SAVE_CLIENT_DESTINATION_BEGIN = 'SAVE_CLIENT_DESTINATION_BEGIN';
export const SAVE_CLIENT_DESTINATION_SUCCESS = 'SAVE_CLIENT_DESTINATION_SUCCESS';
export const SAVE_CLIENT_DESTINATION_FAILURE = 'SAVE_CLIENT_DESTINATION_FAILURE';
export const GET_LIST_CLIENT_DESTINATION_BEGIN = 'GET_LIST_CLIENT_DESTINATION_BEGIN';
export const GET_LIST_CLIENT_DESTINATION_SUCCESS = 'GET_LIST_CLIENT_DESTINATION_SUCCESS';
export const GET_LIST_CLIENT_DESTINATION_FAILURE = 'GET_LIST_CLIENT_DESTINATION_FAILURE';
export const TRANSFER_PROCESS_BEGIN = 'TRANSFER_PROCESS_BEGIN';
export const TRANSFER_PROCESS_SUCCESS = 'TRANSFER_PROCESS_SUCCESS';
export const TRANSFER_PROCESS_FAILURE = 'TRANSFER_PROCESS_FAILURE';